# Generated by Django 4.2.5 on 2023-10-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinary_consultations',
            old_name='diagnostic',
            new_name='diagnosis',
        ),
    ]
